### ISSUE TITLE
Sometimes join link doesn't work

### ISSUE THREAD

**Issue by jackrr** [jackrr/bubble#33]
Need more info, inconsistently reproducible

**Comment by jackrr** [comment]
@dmahfouda let's collect more observations so we can track down + fix

**Comment by dmahfouda** [comment]
![Screen Shot 2021-11-09 at 12 30 39 PM](https://user-images.githubusercontent.com/942062/142305107-0c9d4648-578f-402a-822d-6765c696fbec.jpeg)

I think the issue is that when new members create an account from a join link, they are not shown as having been added to the bubble that they joined.
